[cursor]
style = "Block"

[env]
TERM = "tmux-256color"

[font]
size = 10.5
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

# /opt/bin/zsh is linked in install.sh, make sure Nix installed terminal-tools
[terminal.shell]
args = ["-l"]
program = "/opt/bin/zsh"

[window]
decorations = "full"

[window.padding]
x = 10
y = 10
